/******************************************************************************
 * Top contributors (to current version):
 *   Alex Ozdemir
 *
 * This file is part of the cvc5 project.
 *
 * Copyright (c) 2009-2023 by the authors listed in the file AUTHORS
 * in the top-level source directory and their institutional affiliations.
 * All rights reserved.  See the file COPYING in the top-level source
 * directory for licensing information.
 * ****************************************************************************
 * Manager for proofs related to a given Ideal:
 *  Stores proof of memberships in d_membershipProofs
 *  Produces proofs using branching rules (translation of findZero rules)
 */

#include <vector>

#include "cvc5_private.h"

#if CVC5_USE_COCOA
#ifndef CVC5__THEORY__IDEAL__PROOF_H
#define CVC5__THEORY__IDEAL__PROOF_H

#include <CoCoA/TmpGPoly.H>
#include <CoCoA/ring.H>

#include <functional>
#include <unordered_map>

#include "context/cdlist_forward.h"
#include "proof/proof.h"
#include "smt/env_obj.h"
#include "theory/ff/cocoa_encoder.h"
#include "theory/ff/membership_proof_manager.h"
#include "theory/ff/proof_utils.h"
namespace cvc5::internal {
namespace theory {
namespace ff {

class IdealProofManager : protected EnvObj
{
 public:
  /**
   * Create an object that will contain proofs for a given a ideal.
   * @param The cvc5 enviroment
   * @param id: The id of the proof engine
   * @param inputs: The set of generators.
   * @param cocoaIdeal: The data structure of an ideal in cocoalib.
   */
  IdealProofManager(Env& env,
             CDProof* globalProof,
             size_t id,
             const std::vector<CoCoA::RingElem>& inputs,
             CocoaEncoder& enc,
             CoCoA::ideal cocoaIdeal);
  /**
   * Setup the hooks in cocoalib
   */
  void setFunctionPointers();
  /**
   * Enable execution of the hooks.
   */
  void enableProofHooks();
  /**
   * Disable hook execution.
   */
  void disableProofHooks();

  /**
   * Called when we are branching on the roots of a polynomial. Register this
   * polynomial in the representation.
   * @param branchPoly: The polynomial in which we are branching.
   */
  void registerBranchPolynomial(CoCoA::RingElem branchPoly);

  /**
   * Also called only when we are branching on the rooots of a polynmial.
   * Register the roots of this polynomial in the representation.
   * @param roots: The roots of the branching polynomial.
   */
  void registerRoots(std::vector<CoCoA::RingElem> roots);

  /**
   * Register the distinct-roots gcd witness for the branch polynomial:
   * r = (x^q mod p) - x together with (d, A, B) such that A*p + B*r = d.
   */
  void registerDistinctRootsGcd(const GcdInfo& info);

  /**
   * Register a possible conclusion derived from the current object.
   * A conclusion consists in a disjunct of a branching application, i.e a
   * possible valid assignment.
   * @param choicePoly: A polynomial in the "x - a" format, where x is a
   * non-assigned variable and a fixed element in the finite field. Equivalent
   * to assign x to a.
   * @param newIdeal: The new cocoaIdeal generated by adding the choicePoly to
   * the set of generators.
   * @return An IdealProof object for the newIdeal.
   */
  std::shared_ptr<IdealProofManager> registerBranch(CoCoA::RingElem choicePoly,
                                             CoCoA::ideal newIdeal);
  /**
   * Called only when the branching of the current object is unsat.
   * Register a node in globalTheoryProofs containing the fact that the set of
   * generators does not have any common root.
   * @param rootBranching: Wheter we are branching on roots or by exhaustion.
   * @param globalTheoryProofs: The global theory CDProof enviroment in which we
   * register all proofs of this kind.
   */
  void finishProof(bool rootBranching);

  /**
   * Register the fact that the unit belongs to the ideal i.e that the set of
   * the generators does not have any common root.
   * @param p: The unit.
   * @param globalTheoryProofs: The global theory CDProof enviroment in which we
   * register all proofs of this kind.
   */
  Node oneRefutation(CoCoA::RingElem p);

  /**
   * @return The predicate stating that the variety is empty.
   */
  Node getUnsatFact();

  /**
   * @return The predicate stating that the variety is non empty
   */
  Node getSatFact();

  /**
   * Updates the generators of this ideal. Used for unsat core restriction.
   * @param newGens: The new generators.
   */
  void updateIdeal(std::vector<Node>& newGens);

 private:
  /**
   * Determines the non-assigned variables in the current branch. Used for
   * producing branch proof arguments.
   * @return A vector of Nodes representing those variables
   * */
  std::vector<Node> nonAssignedVars();
  /**
   * Produces and prove the Node that represents the conclusion of branching
   * rules.
   * @param childrenSatFact: A vector of Nodes that represents the assumption
   * that each of the branching disjuncts is SAT.
   * @param rootBranching: Represents the proof step taken. If true, then we are
   * branching on roots of a univariate polynomial, else, the branching is
   * exhaustive.
   * needed. Use CocoA Ideal to compute this. The argument will actually be all
   * TODO
   * *non*-assigned variables.
   */
  Node proveBrancher(std::vector<Node>& childrenSatFact, bool rootBranching);

  /**
   * A representation of the Ideal that we are currently proving membership
   * facts.
   */
  Node d_ideal;

  /**
   * The d_ideal representation in CoCoALib.
   */
  CoCoA::ideal d_cocoaIdeal;
  /**
   * The encoder used during node -> CoCoA translation. Used to get terms
   * associated with indeterminates.
   */
  CocoaEncoder d_enc;

  /**
   * A node representing the fact that our set of generators does not have any
   * common roots.
   * Initialized only when there is a proof for this fact.
   */
  Node d_emptyVarFact;

  /**
   * (Univariate Branching) The polynomial used in the branching steps.
   */
  Node d_branchPoly;

  /**
   * (Univariate Branching) The proof of membership for the branching
   * polynomial.
   */
  Node d_branchPolyProof;

  /**
   * (Univariate Branching) The roots of the above polynomial represented as an
   * sexpr
   */
  Node d_branchPolyRoots;
  /**
   * (Univariate Branching) SEXPR(gcd, bezoutA, bezoutB) — witness that
   * A*p + B*r = d over r = (x^q mod p) - x.
   */
  Node d_branchPolyGcdInfo;
  /**
   * (Univariate Branching) The reduced field polynomial r = (x^q mod p) - x.
   */
  Node d_branchPolyReducedFieldPoly;
  /**
   * (Univariate Branching) The variable that we will be branching through
   */
  Node d_branchVar;
  /**
   * Holds elements in the branching disjunct.
   */
  std::vector<Node> d_childrenUnsat;

  /**
   * Maps string representation of polynomials to their corresponding Nodes.
   */
  std::unordered_map<std::string, Node> d_polyToNode;

  /**
   * The CDProof to record the derivation for this branch.
   */
  CDProof d_proof;

  /**
   * The CDProof where we store relevant facts for the complete proof.
   */
  CDProof* d_globalProof;
  /**
   * The id of the proof object.
   */
  size_t d_id;
  /**
   * Manages membership proofs for polynomials in this ideal.
   */
  MembershipProofManager* d_membershipProofs;
};

}  // namespace ff
}  // namespace theory
}  // namespace cvc5::internal

#endif /* CVC5__THEORY__FF__PROOF_H */

#endif /* CVC5_USE_COCOA */
